### ISSUE TITLE
Cryptex does not autodetect email with country TLD

### ISSUE THREAD

**Issue by topotato** [AndiDittrich/WordPress.Cryptex#1]
Hi, I've been using cryptex for a while but I found out that it does not auto detect emails with country code TLD for example:
admin@abc.tv
admin@abc.my

Please take a look at it. Thanks

**Comment by AndiDittrich** [comment]
Dear topotato,

thank's for your report. i can confim that the autodetection is not working as expected. i will fix it in the next day and add some additional testcases to avoid such problems in the future.

best regards, Andi

**Comment by AndiDittrich** [comment]
Hi, i've fixed the issue. the release v5.1 will follow next week.

**Comment by AndiDittrich** [comment]
v5.1 has been released including the fix!
