### ISSUE TITLE
Use it on WP JOB Manager widget

### ISSUE THREAD

**Issue by beeriz** [AndiDittrich/WordPress.Cryptex#3]
I'm not able to convert the phone and email widget (demo available here : http://wafni.com/listing/the-hoxton/). Any idea how to use Cryptex in any way to protect content not from articles?

**Comment by AndiDittrich** [comment]
Dear beeriz,

you have to modify the Widget Plugin to use the `Cryptex::crypt` function to display the output

**Example**

```php
<?php 
Cryptex::crypt('yourtext'); 
?>
```

In case your plugin supports filters, you can achive this behaviour by adding a custom one.
