### ISSUE TITLE
PHP warnings appear in PHP v7.1

### ISSUE THREAD

**Issue by jotazzu** [AndiDittrich/WordPress.Cryptex#4]
FYI
Using the [email]...[/email] shortcode in PHP v7.1 a PHP Warning:  Illegal string offset 'type' in /usr/www/xxxx/wp-content/plugins/cryptex/class/ShortcodeHandler.php on line 91 is generated. This warning does not occur in PHP v7.0. Unfortunately I can not check the behaviour in PHP v7.2.

**Comment by AndiDittrich** [comment]
HI jotazzu,

thanks for your report! i will check this soon - didn't tested PHP 7.1/7.2 yet

br. Andi

**Comment by AndiDittrich** [comment]
Hi jotazzu,

i can confirm the issue. it is not limited to a special php version. in case the **email** or **telephone** shortcodes are used __without__ additional attributes it will cause this warning.

please try the current master branch with v6.1.0 - this should fix the issue.

best regards, Andi
