### ISSUE TITLE
Disable for specific part

### ISSUE THREAD

**Issue by nelero** [AndiDittrich/WordPress.Cryptex#8]
Hi,
thanks for your plugin.
i'd like to disable cryptx for specific part : 1 widget need a placeholder like "please enter my@email.com". 
But with cryptx placeholder is broken.
I can't disable for the specific page cause there is a mail address in the footer.
I can't disable for all the widgets (i tried but didn't change anything) cause some widgets contain text edited by end users and contain addresses.

Would it be possible to specify a css class on the input, or, tag a widget to disable it only for a part ?

Thanks

**Comment by AndiDittrich** [comment]
Hi @nelero ,

the Cryptex shortcodes + autodetection are implemented as PHP content filters...therefore it is impossible to exclude specific elements using a css class.

but there are a few ways to solve your issue:

* Just disable cryptex autodetection for widgets (Cryptex -> Options > Autodetection -> Filter Targets -> widget_text)
* Exclude the page from autodetection and use shortcodes for your footer

best regards, Andi
