### ISSUE TITLE
No more image will be created

### ISSUE THREAD

**Issue by rmfberlin** [AndiDittrich/WordPress.Cryptex#9]
HI, I used your wonderfull plugin for years. Today I realised, that no image will be created. Look here: [https://rmf.berlin/impressum/] WP 5.4.2, PHP 7.4, Cryptex 7.1
Best regards 
Rainer

**Comment by AndiDittrich** [comment]
do you get any php errors in your server logfiles ?

**Comment by AndiDittrich** [comment]
the inline css code is also broken on your page - what did you changed ?

**Comment by rmfberlin** [comment]
now it's working. I changed the Hdpi Renderer from CSS Image to HTML5 srcset
